apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.gitlab.com": {
          "username": "YOUR_GITLAB_USERNAME",
          "password": "YOUR_PERSONAL_ACCESS_TOKEN"
        }
      }
    }
