name: Build, Test, and Publish Docker Image

on: [push, pull_request]

jobs:
  Publish-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test > Publish-Docker-Image-output-${{ github.run_number }}.txt

      - name: Archive Test and Build Results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_number }}-Publish-Docker-Image-output
          path: Publish-Docker-Image-output-${{ github.run_number }}.txt

      - name: Log in to GitLab Docker Registry
        run: echo ${{ secrets.GITLAB_ACCESS_TOKEN }} | docker login registry.gitlab.com -u ${{ secrets.GITLAB_USERNAME}} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.gitlab.com/${{ secrets.PROJECT_NAME}}/${{ secrets.REPO_NAME}}:nodejs-example-${{ github.sha }} .
          docker push registry.gitlab.com/${{ secrets.PROJECT_NAME}}/${{ secrets.REPO_NAME}}:nodejs-example-${{ github.sha }}     
